baseurl      = "https://www.shubhisroking.me/"
title        = "shubhisroking"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Versatile dev, exploring new horizons"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Shubh's personal website"
  keywords = "shubhisroking, homepage, blog"
  images = [""]

  [params.portrait]
    path     = "/img/avatar.png"
    alt      = "Avatar"
    maxWidth = "50px"
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/shubhisroking"

  [[params.social]]
    name = "email"
    url  = "mailto:shubhisroking@proton.me"

  [[params.social]]
    name = "github"
    url  = "https://github.com/shubhisroking"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/shubhisrocking"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[languages]
  [languages.en]
    title = "shubhisroking"
    # subtitle = "Versatile dev, exploring new horizons"
    # keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    # readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "shubisroking"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#   [[menu.main]]
#     identifier = "abput"
#     name       = "About"
#     url        = "/about"

logoCursorDisabled = true
enableRobotsTXT = true
